version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chirp
    volumes:
      - chirp_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: chirp
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL}
    image: chirp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  chirp_db:
